// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBqbwQkbVkXn7q9ozEJh2sXCVZsAwaIM',
    appId: '1:1025504039976:web:29d7cc5f5ac8995b9ed11d',
    messagingSenderId: '1025504039976',
    projectId: 'authorizaton-tutorial',
    authDomain: 'authorizaton-tutorial.firebaseapp.com',
    storageBucket: 'authorizaton-tutorial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc0_byHxMb3CfCa7oXyADa0KnpqVqkhM8',
    appId: '1:1025504039976:android:49e6a8aa305e64699ed11d',
    messagingSenderId: '1025504039976',
    projectId: 'authorizaton-tutorial',
    storageBucket: 'authorizaton-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ42v0vESxtE891vXOM_vObS4uVYCFYks',
    appId: '1:1025504039976:ios:1223c23a5e6b00459ed11d',
    messagingSenderId: '1025504039976',
    projectId: 'authorizaton-tutorial',
    storageBucket: 'authorizaton-tutorial.appspot.com',
    iosBundleId: 'com.example.authlearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ42v0vESxtE891vXOM_vObS4uVYCFYks',
    appId: '1:1025504039976:ios:51f7c11aa0dc55829ed11d',
    messagingSenderId: '1025504039976',
    projectId: 'authorizaton-tutorial',
    storageBucket: 'authorizaton-tutorial.appspot.com',
    iosBundleId: 'com.example.authlearning.RunnerTests',
  );
}
